# Generated by Django 5.0.4 on 2024-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_activation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='activation_code',
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
